List missing tools in file missing_tools

diff --git a/grml-hwinfo b/grml-hwinfo
--- a/grml-hwinfo
+++ b/grml-hwinfo
@@ -84,7 +84,12 @@ if [ -z "$1" ] ; then
    echo 'Usage: exectest <binary>'>&2
    return 1
 else
-   test -e "$(which $1)" && return 0 || return 1
+   if test -e "$(which $1)" ; then
+     return 0
+   else
+     grep -q "^$1"'$' missing_tools 2>/dev/null || echo "$1" >> missing_tools
+     return 1
+   fi
 fi
 }
 
